name: wolt_test_task
description: Test task for the Wolt

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  dio: 5.1.0
  freezed_annotation: 2.0.3
  flutter_bloc: 8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.11
  flutter_lints: 2.0.1
  freezed: 2.0.3
  fake_async: 1.3.0

flutter:
  uses-material-design: true
